### ISSUE TITLE
memory leak when deleting irSignal

### ISSUE THREAD

**Issue by sanelss** [bengtmartensson/Infrared4Arduino#14]
When attempting to update an irSignal with new codes by calling Pronto::parse(...) again it leads to memory leak. even when attempting to delete irSignal before parse call issue persists.

Console output:

start 1517
After irSignal Assignment: 1324
IrSenderPwm::getInstance(true)->sendIrSignal 1319
IrSenderPwm::getInstance(true)->sendIrSignal 1319
IrSenderPwm::getInstance(true)->sendIrSignal 1319
after delete: 1319
After irSignal Assignment: 1292
after delete: 1319
After irSignal Assignment: 1283
after delete: 1310
After irSignal Assignment: 1236
after delete: 1310
After irSignal Assignment: 1236
after delete: 1310
After irSignal Assignment: 1209
after delete: 1310
After irSignal Assignment: 1209
after delete: 1310
After irSignal Assignment: 1191
after delete: 1218
After irSignal Assignment: 1144
after delete: 1218
After irSignal Assignment: 1144
after delete: 1218
After irSignal Assignment: 1117
after delete: 1218
After irSignal Assignment: 1117
after delete: 1218
steve

code:

// Sends a signal in Pronto format

#include <IrSenderPwm.h>
#include <Pronto.h>

IrSignal *irSignal;

static const uint16_t power[] = {0x0000, 0x006D, 0x0012, 0x0012, 0x0008, 0x0022, 0x0008, 0x0041, 0x0008, 0x001D, 0x0008, 0x006A, 0x0008, 0x0032, 0x0008, 0x0032, 0x0008, 0x002C, 0x0008, 0x0065, 0x0008, 0x020C, 0x0008, 0x0022, 0x0008, 0x001D, 0x0008, 0x001D, 0x0008, 0x001D, 0x0008, 0x001D, 0x0008, 0x006A, 0x0008, 0x001D, 0x0008, 0x001D, 0x0008, 0x0BEF, 0x0008, 0x0022, 0x0008, 0x0041, 0x0008, 0x001D, 0x0008, 0x006A, 0x0008, 0x0032, 0x0008, 0x0032, 0x0008, 0x002C, 0x0008, 0x0065, 0x0008, 0x020C, 0x0008, 0x0022, 0x0008, 0x0046, 0x0008, 0x0046, 0x0008, 0x001D, 0x0008, 0x001D, 0x0008, 0x006A, 0x0008, 0x001D, 0x0008, 0x001D, 0x0008, 0x0BEF};
static const uint16_t guide[] = {0x0000, 0x006C, 0x0012, 0x0012, 0x0008, 0x0023, 0x0008, 0x0043, 0x0008, 0x001D, 0x0008, 0x006E, 0x0008, 0x0033, 0x0008, 0x0033, 0x0008, 0x002D, 0x0008, 0x0068, 0x0008, 0x01F3, 0x0008, 0x0023, 0x0008, 0x003D, 0x0008, 0x001D, 0x0008, 0x001D, 0x0008, 0x0028, 0x0008, 0x0043, 0x0008, 0x001D, 0x0008, 0x001D, 0x0008, 0x0C45, 0x0008, 0x0023, 0x0008, 0x0043, 0x0008, 0x001D, 0x0008, 0x006E, 0x0008, 0x0033, 0x0008, 0x0033, 0x0008, 0x002D, 0x0008, 0x0068, 0x0008, 0x01F3, 0x0008, 0x0023, 0x0008, 0x0068, 0x0008, 0x0048, 0x0008, 0x001D, 0x0008, 0x0028, 0x0008, 0x0043, 0x0008, 0x001D, 0x0008, 0x001D, 0x0008, 0x0C45};

void setup() {
  Serial.begin(250000);
  Serial.print("start ");
  Serial.println(freeRam());

  irSignal=Pronto::parse(power,sizeof(power)/sizeof(power[0]));
  Serial.print("After irSignal Assignment: ");
  Serial.println(freeRam());
  
  IrSenderPwm::getInstance(true)->sendIrSignal(*irSignal);
  Serial.print("IrSenderPwm::getInstance(true)->sendIrSignal ");
  Serial.println(freeRam());
  Serial.print("IrSenderPwm::getInstance(true)->sendIrSignal ");
  Serial.println(freeRam());
  Serial.print("IrSenderPwm::getInstance(true)->sendIrSignal ");
  Serial.println(freeRam());
  delete irSignal;
  Serial.print("after delete: ");
  Serial.println(freeRam());

  irSignal=Pronto::parse(power,sizeof(power)/sizeof(power[0]));
  Serial.print("After irSignal Assignment: ");
  Serial.println(freeRam());

  delete irSignal;
  Serial.print("after delete: ");
  Serial.println(freeRam());

  irSignal=Pronto::parse(power,sizeof(power)/sizeof(power[0]));
  Serial.print("After irSignal Assignment: ");
  Serial.println(freeRam());

  delete irSignal;
  Serial.print("after delete: ");
  Serial.println(freeRam());

  irSignal=Pronto::parse(power,sizeof(power)/sizeof(power[0]));
  Serial.print("After irSignal Assignment: ");
  Serial.println(freeRam());

  delete irSignal;
  Serial.print("after delete: ");
  Serial.println(freeRam());

  irSignal=Pronto::parse(power,sizeof(power)/sizeof(power[0]));
  Serial.print("After irSignal Assignment: ");
  Serial.println(freeRam());

  delete irSignal;
  Serial.print("after delete: ");
  Serial.println(freeRam());

  irSignal=Pronto::parse(power,sizeof(power)/sizeof(power[0]));
  Serial.print("After irSignal Assignment: ");
  Serial.println(freeRam());

  delete irSignal;
  Serial.print("after delete: ");
  Serial.println(freeRam());

  irSignal=Pronto::parse(power,sizeof(power)/sizeof(power[0]));
  Serial.print("After irSignal Assignment: ");
  Serial.println(freeRam());

  delete irSignal;
  Serial.print("after delete: ");
  Serial.println(freeRam());

  irSignal=Pronto::parse(power,sizeof(power)/sizeof(power[0]));
  Serial.print("After irSignal Assignment: ");
  Serial.println(freeRam());

  delete irSignal;
  Serial.print("after delete: ");
  Serial.println(freeRam());

  irSignal=Pronto::parse(power,sizeof(power)/sizeof(power[0]));
  Serial.print("After irSignal Assignment: ");
  Serial.println(freeRam());

  delete irSignal;
  Serial.print("after delete: ");
  Serial.println(freeRam());

  irSignal=Pronto::parse(power,sizeof(power)/sizeof(power[0]));
  Serial.print("After irSignal Assignment: ");
  Serial.println(freeRam());

  delete irSignal;
  Serial.print("after delete: ");
  Serial.println(freeRam());

  irSignal=Pronto::parse(power,sizeof(power)/sizeof(power[0]));
  Serial.print("After irSignal Assignment: ");
  Serial.println(freeRam());

  delete irSignal;
  Serial.print("after delete: ");
  Serial.println(freeRam());

  irSignal=Pronto::parse(power,sizeof(power)/sizeof(power[0]));
  Serial.print("After irSignal Assignment: ");
  Serial.println(freeRam());

  delete irSignal;
  Serial.print("after delete: ");
  Serial.println(freeRam());
  
  Serial.println("steve");
}

void loop() {
}

int freeRam() {
    extern int __heap_start, *__brkval;
    int v;
    return (int) &v - (__brkval == 0 ? (int) &__heap_start : (int) __brkval);
}

**Comment by bengtmartensson** [comment]
@sanelss ;
thank you very much for this bug report.
