### ISSUE TITLE
ESP32: pinMode, readDigital/writeDigital stops working when #include <IrReceiverSampler.h>

### ISSUE THREAD

**Issue by Carsstengithub** [bengtmartensson/Infrared4Arduino#57]
Trying the blink example, but when <IrReceiverSampler.h> is included in the standard blink example it stops working on a 
ESP32 Dev Board (Blinking PIN 2), other pins also stops working. But the example IrReceiverSampler works fine, but then I'm unable to use other pins for controlling a relay etc.

Has this something to do with #54 ?

**Comment by bengtmartensson** [comment]
Please post a full sketch. 

> Has this something to do with #54 ?

Unlikely; if that bites, compilation will fail.

**Comment by Carsstengithub** [comment]
Fulle sketch:
//If this is included it does not work
#include <IrReceiverSampler.h>

#define PIN 2

void setup() {
  pinMode(PIN, OUTPUT);
}

void loop() {
  digitalWrite(PIN, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);                       // wait for a second
  digitalWrite(PIN, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);                       // wait for a second
}

**Comment by AVDeveloppement** [comment]
Hello, i have same problem with a esp32 can't use a relay, pin don't change
with Arduino nano it work my relay are triggered.
Strange

**Comment by shawnchu** [comment]
enum OUTPUT value is 1 in PinModeStatus.h but 2 for ESP:
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/esp32-hal-gpio.h#L45

The RISING, FALLING enums changed orignal value too.

The best option might be moving the definition to Esp32.h ?

**Comment by bengtmartensson** [comment]
I pushed a proposed fix to branch PinModeStatus. Only change is to [PinModeStatus.h](https://github.com/bengtmartensson/Infrared4Arduino/blob/PinModeStatus/src/PinModeStatus.h). Please test.

**Comment by shawnchu** [comment]
Thanks & Verified!

**Comment by AVDeveloppement** [comment]
Thanks for your work
