### ISSUE TITLE
Check out I2S to send the IR signal on ESP8266

### ISSUE THREAD

**Issue by probonopd** [bengtmartensson/Infrared4Arduino#73]
The ESP8266 is still arguably one of the least expensive and most popular devices to send infrared codes from WLANs.

https://shepherdingelectrons.blogspot.com/2018/10/the-ir-egg-voice-controlled-esp8266-i2s.html?view=magazine describes how to use I2S to accurately control output to a GPIO pin. Maybe it is of interest to you.

**Comment by bengtmartensson** [comment]
Thank you for the suggestion. Closing as duplicate of #5, where I also more give more detailed comments.
