### ISSUE TITLE
Memory leak in RC5Renderer example

### ISSUE THREAD

**Issue by Z4urce** [bengtmartensson/Infrared4Arduino#89]
As the title says, there's a memory leak in the Rc5Renderer example. Can't loop more than 10 times on an UNO.

**Comment by bengtmartensson** [comment]
Thank you very much for this report. Background: if you generate an object with Rc5Renderer::newIrSignal, this makes an implicit `new` so the object must be manually `delete`-d.

Have checked in a fixed version.

**Comment by bengtmartensson** [comment]
... and released it as version 1.2.3 (together with some Doxygen tweaks); should be available in the Arduino library manager shortly.
